export const opportunities = [
  {
    id: "mantle-turing-test-2026",
    name: "The Turing Test Hackathon 2026",
    type: "hackathon",
    status: "active",
    source: "DoraHacks official page, verified 2026-05-28",
    url: "https://dorahacks.io/hackathon/mantleturingtesthackathon2026/detail",
    applyUrl: "https://dorahacks.io/hackathon/mantleturingtesthackathon2026/detail",
    deadline: "2026-06-15",
    prize: "$100K Phase 2 prize pool on DoraHacks; $120K total across phases in announcement copy",
    ecosystem: ["Mantle Network", "AI Agents", "Byreal", "On-chain data", "RWA", "Trading"],
    requirements: [
      "Submit open-source repo, runnable demo, and project pitch",
      "Deploy on Mantle Network for Grand Champion, Alpha/Data, and AI/RWA tracks",
      "Use Mantle on-chain data as a core data source for Alpha/Data",
      "Build AI DevTools such as submission audits, smart gas tooling, or Mantle-specific assistants",
      "Use Byreal Agent Skills, Byreal Perps CLI, or RealClaw for Agentic Economy",
      "Demo video or public frontend link required for UI/deployment awards"
    ],
    fitNotes: "Best active Web3 target: still open on DoraHacks, strong AI DevTools/on-chain proof narrative, and clear scoring criteria. Real deployment remains gated behind wallet approval.",
    effortDays: 7,
    directCashSpeed: 1,
    upside: 9,
    aiFit: 10,
    web3Fit: 10,
    proofQuality: 10,
    riskFlags: [
      "DoraHacks login required for final submission",
      "Competitive prize, not guaranteed income",
      "Mantle deployment needs a wallet and testnet/mainnet transaction approval",
      "Byreal/RealClaw integration may require additional account or SDK setup"
    ]
  },
  {
    id: "bags-hackathon-2026",
    name: "The Bags Hackathon",
    type: "hackathon",
    status: "expired",
    source: "DoraHacks official page overrode stale StartupCash listing",
    url: "https://dorahacks.io/hackathon/the-bags-hackathon/detail",
    applyUrl: "https://dorahacks.io/hackathon/the-bags-hackathon/detail",
    deadline: "2026-05-12",
    prize: "$1M listed by DoraHacks, but submission period ended",
    ecosystem: ["Solana", "Bags", "AI Agents", "Payments"],
    requirements: [
      "Build on Bags platform",
      "GitHub repo required",
      "Demo video required",
      "Register on DoraHacks"
    ],
    fitNotes: "Good conceptual fit, but no longer actionable because the official DoraHacks submission deadline passed.",
    effortDays: 4,
    directCashSpeed: 0,
    upside: 10,
    aiFit: 10,
    web3Fit: 10,
    proofQuality: 7,
    riskFlags: ["Submission period ended", "Third-party deadline was stale", "Bags API auth requires wallet signature"]
  },
  {
    id: "uipath-agenthack-2026",
    name: "UiPath Global AgentHack 2026",
    type: "hackathon",
    status: "active",
    source: "UiPath PRNewswire announcement",
    url: "https://www.prnewswire.com/in/news-releases/uipath-launches-global-agenthack-2026-at-devcon-bengaluru-302773236.html",
    applyUrl: "https://uipath-agenthack.devpost.com/",
    deadline: "2026-06-29",
    prize: "$48,000 prize pool, $8,000 grand prize",
    ecosystem: ["Agentic orchestration", "Enterprise automation", "Devpost"],
    requirements: [
      "Public GitHub repository",
      "Demo video",
      "Use UiPath platform/coding agents"
    ],
    fitNotes: "Strong backup if Bags access blocks us; less Web3, more enterprise agent workflow.",
    effortDays: 10,
    directCashSpeed: 1,
    upside: 7,
    aiFit: 9,
    web3Fit: 1,
    proofQuality: 9,
    riskFlags: ["Requires UiPath platform fit", "Longer judging cycle"]
  },
  {
    id: "nandahack-agentic-ai-2026",
    name: "NandaHack Agentic AI Hackathon",
    type: "hackathon",
    status: "active",
    source: "MIT Media Lab / HCLTech event site",
    url: "https://nandahack.media.mit.edu/",
    applyUrl: "https://nandahack.media.mit.edu/",
    deadline: "2026-06-11",
    prize: "Visibility and finalist event; prize details not emphasized on page",
    ecosystem: ["Enterprise AI agents", "Agent infrastructure", "OpenClaw"],
    requirements: [
      "Working prototype",
      "Clear documentation",
      "Short demo showing problem, approach, impact"
    ],
    fitNotes: "Great narrative fit for practical agent infrastructure, but not Web3 and not direct cash.",
    effortDays: 9,
    directCashSpeed: 0,
    upside: 5,
    aiFit: 10,
    web3Fit: 0,
    proofQuality: 9,
    riskFlags: ["May require application acceptance", "Cash prize unclear"]
  },
  {
    id: "web3-career-opportunity-pool",
    name: "web3.career AI/Product opportunity pool",
    type: "job-pipeline",
    status: "active",
    source: "web3.career jobs listing",
    url: "https://web3.career/crypto-jobs",
    applyUrl: "https://web3.career/crypto-jobs",
    deadline: null,
    prize: "Long-term salary or contract work, not a hackathon prize",
    ecosystem: ["Web3 jobs", "AI", "Product", "Remote"],
    requirements: [
      "Profile or direct job application",
      "Role-specific resume/portfolio",
      "Often longer hiring cycle"
    ],
    fitNotes: "Useful as a source pool for the agent; weak for earning 100 RMB quickly.",
    effortDays: 14,
    directCashSpeed: 0,
    upside: 8,
    aiFit: 6,
    web3Fit: 8,
    proofQuality: 8,
    riskFlags: ["Hiring cycle is slow", "Not a competition"]
  }
];
